export enum TriangleToolboxMessage {
  ActivateStarOfDavid = 'activate-star-of-david',
  ActivateTriangleCorners = 'activate-triangle-corners',
  ActivateTriangleMidpoints = 'activate-triangle-midpoints',
  ActivateTriangleMidpointsPlus = 'activate-triangle-midpoints-plus',
  ActivateTriangleCenter = 'activate-triangle-center',
  ChangeColor = 'change-color',
  ChangeCounterValues = 'change-counter-values',
  ChangeMode = 'change-mode',
  ChangeRowCount = 'change-row-count',
  DrawLines = 'draw-lines',
  EraseLines = 'erase-lines',
  ClearActive = 'clear-active',
  ClearAll = 'clear-all',
  ClearColor = 'clear-color',
  SelectEven = 'select-even',
  SelectOdd = 'select-odd',
  ToggleAlign = 'toggle-align',
  ToggleLineLength = 'toggle-line-length',
  ToggleShowValues = 'toggle-show-values'
}
