export enum TriangleToolboxMessage {
  StarOfDavid = 'star-of-david',
  TriangleCorners = 'activate-triangle-corners',
  TriangleMidpoints = 'activate-triangle-midpoints',
  TriangleMidpointsPlus = 'activate-triangle-midpoints-plus',
  TriangleCenter = 'activate-triangle-center',
  TriangleSide = 'activate-triangle-side',
  ChangeColor = 'change-color',
  ChangeCounterValues = 'change-counter-values',
  ChangeMode = 'change-mode',
  ChangeRowCount = 'change-row-count',
  CycleLineDirections = 'cycle-line-directions',
  DrawLines = 'draw-lines',
  EraseLines = 'erase-lines',
  ClearActive = 'clear-active',
  ClearAll = 'clear-all',
  ClearColor = 'clear-color',
  Multiple = 'multiple',
  ToggleAlign = 'toggle-align',
  ToggleLineLength = 'toggle-line-length',
  ToggleShowValues = 'toggle-show-values'
}
